Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -213,8 +213,10 @@ jobs:
 
       - name: Purge ***REMOVED***s using BFG
         run: |
+          cat ***REMOVED***s.txt
           echo "Purging ***REMOVED***s using BFG Repo-Cleaner..."
-          bfg --replace-text ***REMOVED***s.txt
+          java -jar ../bfg.jar --replace-text ***REMOVED***s.txt || { echo "❌ BFG failed"; exit 1; }
+          #bfg --replace-text ***REMOVED***s.txt
           echo "Cleaning up repository..."
           git reflog expire --expire=now --all && git gc --prune=now --aggressive
           echo "✅ Secrets purged using BFG Repo-Cleaner"
